Анализ массива с помощью NumPy в Python
Это задание не проверяется LMS, но выполняя его, вы тренируете и закрепляете навыки работы с функциями библиотеки NumPy на различных исходных данных.

Для этого задания вы можете использовать любой доступный вам набор данных. Либо можно сгенерировать NumPy массив самостоятельно. 

Что нужно сделать:

1.	Создайте Python-ноутбук, загрузите в него данные из csv-файла и преобразуйте в массив NumPy. Либо сгенерируйте массив самостоятельно.

2.	Получите атрибуты массива — число измерений, размеры массива, количество элементов, тип данных элементов.

3.	Потренируйтесь в выборке элемента по индексу и выполнении срезов данных массива.

4.	Потренируйтесь в выполнении математических и статистических функций библиотеки NumPy — найдите сумму элементов, среднее значение, медиану, отклонение от среднего и другие показатели, которые считаете полезными при анализе исходного массива.

По каждому пункту задания сделайте выводы и отразите их в созданном Python-ноутбуке. В качестве решения задания прикрепите ссылку на свой ноутбук.

In [1]:
import csv
import pandas as pd
import numpy as np

In [2]:
data = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
data

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [3]:
filename = 'array.csv'

with open(filename, 'w', newline='') as f:
    writer = csv.writer(f)
    
    for i in np.arange(data.shape[0]):
        
        writer.writerow(data[i, :])
        
array_pd = pd.read_csv(filename, header=None)
array_pd

0   1   2   3
0  1   2   3   4
1  5   6   7   8
2  9  10  11  12

In [4]:
array = array_pd.to_numpy()
array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]], dtype=int64)

In [5]:
print(f"dims = {array.ndim}")
print(f"shape = {array.shape}")
print(f"size = {array.size}")
print(f"type = {array.dtype}")

dims = 2
shape = (3, 4)
size = 12
type = int64


In [6]:
print(f"1st row : \n{array[0, :]}\n")
print(f"3rd column : \n{array[:, 3]}\n")
print(f"rows 1, 3 : \n{array[[0, 2], :]}\n")
print(f"odd columns : \n{array[:, ::2]}\n")
print(f"odd rows and columns : \n{array[::2, ::2]}\n")

1st row : 
[1 2 3 4]

3rd column : 
[ 4  8 12]

rows 1, 3 : 
[[ 1  2  3  4]
 [ 9 10 11 12]]

odd columns : 
[[ 1  3]
 [ 5  7]
 [ 9 11]]

odd rows and columns : 
[[ 1  3]
 [ 9 11]]



In [7]:
print(f"N\t: {array.size}")
print(f"sum\t: {np.sum(array)}")
print(f"max\t: {np.max(array)}")
print(f"min\t: {np.min(array)}")
print(f"med\t: {np.median(array)}")
print(f"avg\t: {np.mean(array)}")
print(f"st_dev\t: {np.std(array):.2f}")

N	: 12
sum	: 78
max	: 12
min	: 1
med	: 6.5
avg	: 6.5
st_dev	: 3.45
